os: linux
language: node_js
sudo: false
node_js: 8

install:
- npm install jsonlint -g

script:
- jsonlint ./snippets/python.json
- jsonlint ./snippets/xml.json

before_deploy:
- npm install -g vsce;
- vsce package;

deploy:
  provider: script
  script: vsce publish -p ${VSCODE}
  skip_cleanup: true
  on:
    repo: mstuttgart/odoo-vscode-snippets
    tags: true
