os: linux
language: node_js

sudo: false

node_js: 8

before_deploy:
- npm install -g vsce;
- vsce package;

deploy:
- provider: releases
  github-token: $GITHUB_VSCODE
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: mstuttgart/odoo-vscode-snippets
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  script: vsce publish -p $VSCODE
  skip_cleanup: true
  on:
    repo: mstuttgart/odoo-vscode-snippets
    tags: true
    condition: $TRAVIS_OS_NAME = linux